import { HotelItem, NeighborhoodData, UserConstraints } from "@/types/relocation";

export const DEMO_BENCHMARK_DATE = "September 2026";

export const DEFAULT_DEMO_CONSTRAINTS: UserConstraints = {
  city: "Bangalore",
  officeLocation: "Whitefield (ITPB / Prestige Shantiniketan)",
  salaryLpa: 15,
  budgetMonthlyInr: 25000,
  maxCommuteMin: 30,
  accommodationType: "1BHK",
  furnishedPreference: "furnished",
  gymRequired: true,
  maxGymDistKm: 2,
  foodPreference: "diverse",
  transitPreference: "metro_priority",
  groceryPreference: "walkable_supermarket",
  additionalNotes: "Moving for a software engineer role. Prefer peaceful surroundings, quick access to gym, and good dining.",
  demoMode: true,
};

export const DEMO_NEIGHBORHOODS: NeighborhoodData[] = [
  {
    id: "nallurhalli",
    name: "Nallurhalli",
    city: "Bangalore",
    coordinates: {
      lat: 12.9738,
      lng: 77.7289,
    },
    overview:
      "A peaceful residential pocket situated between Borewell Road and Whitefield Main Road. Highly favored by tech professionals at ITPB and Sigma Tech Park for its quiet lanes, strong gym density, and tree-lined society compounds.",
    estimatedRent: {
      bhk1: { min: 21000, max: 26000 },
      bhk2: { min: 32000, max: 40000 },
      confidence: "verified_market_range",
      sourceSummary: "Locality survey via 99acres & MagicBricks listings (Q3 2026)",
      sources: [
        {
          title: "99acres - Rent Trends in Nallurhalli, Whitefield",
          url: "https://www.google.com/search?q=average+rent+nallurhalli+whitefield+bangalore+99acres",
          query: "average rent in Nallurhalli Whitefield Bangalore",
          engine: "google",
          accessedAt: "2026-09-18T10:30:00Z",
          isCachedDemo: true,
        },
        {
          title: "Housing.com - Locality Guide: Nallurhalli",
          url: "https://www.google.com/search?q=nallurhalli+locality+guide+housing",
          query: "Nallurhalli Whitefield residential locality review",
          engine: "google",
          accessedAt: "2026-09-18T10:32:00Z",
          isCachedDemo: true,
        },
      ],
    },
    commute: {
      estimatedMinutes: 18,
      peakMinutes: 28,
      distanceKm: 3.2,
      mode: "Two-wheeler / Cab / Bus",
      routeDescription: "Via Borewell Road & ECC Road straight to ITPB / International Tech Park.",
      isEstimate: false,
    },
    gyms: {
      countWithinRadius: 6,
      nearestDistanceKm: 0.6,
      items: [
        {
          id: "gym-nal-1",
          title: "Cult.fit Nallurhalli",
          rating: 4.8,
          reviewsCount: 382,
          address: "Borewell Main Rd, Nallurhalli, Whitefield",
          distanceKm: 0.6,
          category: "Fitness Center / Group Classes",
          link: "https://www.google.com/maps/search/Cult+fit+Nallurhalli+Whitefield",
          snippet: "Clean facility, certified trainers, strength and conditioning plus boxing.",
        },
        {
          id: "gym-nal-2",
          title: "Snap Fitness 24/7 Whitefield",
          rating: 4.5,
          reviewsCount: 219,
          address: "Near Nallurhalli Junction, Whitefield",
          distanceKm: 1.1,
          category: "24-Hour Gym",
          link: "https://www.google.com/maps/search/Snap+Fitness+Whitefield",
          snippet: "Open 24 hours with modern cardio and free-weights setup.",
        },
        {
          id: "gym-nal-3",
          title: "Iron Core Fitness Studio",
          rating: 4.7,
          reviewsCount: 145,
          address: "ECC Road, Nallurhalli",
          distanceKm: 0.9,
          category: "Gym & Personal Training",
          link: "https://www.google.com/maps/search/Iron+Core+Fitness+Studio+Whitefield",
        },
      ],
    },
    restaurants: {
      countFound: 24,
      vibe: "Cozy cafes, South Indian breakfast spots, and modern bistros along Borewell Road",
      topHighlights: [
        {
          id: "res-nal-1",
          title: "Third Wave Coffee - Borewell Road",
          rating: 4.6,
          reviewsCount: 540,
          address: "Borewell Rd, Whitefield",
          priceLevel: "₹₹",
          link: "https://www.google.com/maps/search/Third+Wave+Coffee+Borewell+Rd",
          snippet: "Great work ambiance, high-speed WiFi, artisanal brews.",
        },
        {
          id: "res-nal-2",
          title: "Udupi Aathithya Grand",
          rating: 4.4,
          reviewsCount: 1120,
          address: "Nallurhalli Main Road",
          priceLevel: "₹",
          link: "https://www.google.com/maps/search/Udupi+Aathithya+Nallurhalli",
          snippet: "Popular daily breakfast hub for dosas, filter coffee, and thalis.",
        },
        {
          id: "res-nal-3",
          title: "The Fatty Bao / Toast & Tonic (Delivery hub)",
          rating: 4.5,
          reviewsCount: 420,
          address: "Whitefield Main Rd",
          priceLevel: "₹₹₹",
          link: "https://www.google.com/maps/search/Fatty+Bao+Whitefield",
        },
      ],
    },
    groceries: {
      countFound: 12,
      quickCommerceAvailable: true,
      items: [
        {
          id: "groc-nal-1",
          title: "Nature's Basket Whitefield",
          rating: 4.4,
          reviewsCount: 680,
          address: "Borewell Road, Nallurhalli",
          distanceKm: 0.8,
          link: "https://www.google.com/maps/search/Natures+Basket+Whitefield",
        },
        {
          id: "groc-nal-2",
          title: "Blinkit / Zepto Local Dark Store Hub",
          rating: 4.9,
          address: "Nallurhalli Industrial Area",
          distanceKm: 0.5,
          snippet: "8-12 minute rapid grocery delivery active across the entire locality.",
        },
        {
          id: "groc-nal-3",
          title: "MK Retail Supermarket",
          rating: 4.3,
          reviewsCount: 410,
          address: "Near Nallurhalli Bus Stop",
          distanceKm: 0.4,
        },
      ],
    },
    transit: {
      nearestMetroStation: "Nallurhalli Metro Station (Purple Line)",
      metroDistanceKm: 1.4,
      hasDirectBus: true,
      transitItems: [
        {
          id: "trans-nal-1",
          title: "Nallurhalli Metro Station",
          rating: 4.5,
          address: "Whitefield Main Rd, Purple Line",
          distanceKm: 1.4,
          link: "https://www.google.com/maps/search/Nallurhalli+Metro+Station",
        },
        {
          id: "trans-nal-2",
          title: "Nallurhalli Bus Stop (BMTC)",
          distanceKm: 0.3,
          snippet: "Frequent 500-D and V-335E Volvo buses toward ITPL and Silk Board.",
        },
      ],
    },
    reviewThemes: [
      {
        sentiment: "positive",
        topic: "Livability",
        text: "Quiet residential ambiance compared to the noisy main highway; very green societies.",
        sampleCount: 48,
      },
      {
        sentiment: "positive",
        topic: "Gym & Lifestyle",
        text: "Cult.fit and local gyms are within walking distance on Borewell Road.",
        sampleCount: 31,
      },
      {
        sentiment: "negative",
        topic: "Road Width & Peak Traffic",
        text: "Borewell Road becomes bottlenecked during 9:00 AM and 7:00 PM peak rush hours.",
        sampleCount: 22,
      },
    ],
    pros: [
      "Rent fits within ₹22k–₹25k target for high-quality furnished 1BHKs",
      "Cult.fit is only 600m away (well within 2 km requirement)",
      "Borewell Road has active cafe culture and multiple supermarkets",
      "Purple Line Metro (Nallurhalli Station) is just 1.4 km away",
    ],
    cons: [
      "Borewell Road experiences bottlenecks during 9-10 AM office entry",
      "Occasional water tanker reliance during late summer months",
    ],
    sources: [
      {
        title: "Google Local - Gyms near Nallurhalli Bangalore",
        url: "https://www.google.com/maps/search/gyms+near+Nallurhalli+Whitefield",
        query: "gyms near Nallurhalli Whitefield Bangalore",
        engine: "google_local",
        accessedAt: "2026-09-18T10:35:00Z",
        isCachedDemo: true,
      },
      {
        title: "Google Local - Restaurants & Cafes in Borewell Rd Whitefield",
        url: "https://www.google.com/maps/search/restaurants+borewell+road+whitefield",
        query: "restaurants cafes Borewell Road Whitefield",
        engine: "google_local",
        accessedAt: "2026-09-18T10:36:00Z",
        isCachedDemo: true,
      },
    ],
  },

  {
    id: "brookefield",
    name: "Brookefield",
    city: "Bangalore",
    coordinates: {
      lat: 12.9642,
      lng: 77.7138,
    },
    overview:
      "A prime urban residential hub featuring the popular AECS Layout and Kundalahalli Gate junction. Boasts one of eastern Bangalore's highest densities of multi-cuisine restaurants, brewpubs, and fitness centers.",
    estimatedRent: {
      bhk1: { min: 23000, max: 28000 },
      bhk2: { min: 35000, max: 45000 },
      confidence: "verified_market_range",
      sourceSummary: "Aggregated listing data from MagicBricks & NoBroker (Q3 2026)",
      sources: [
        {
          title: "MagicBricks - Brookefield Rental Overview",
          url: "https://www.google.com/search?q=brookefield+bangalore+average+rent+magicbricks",
          query: "Brookefield Bangalore 1BHK rent trends",
          engine: "google",
          accessedAt: "2026-09-18T10:40:00Z",
          isCachedDemo: true,
        },
      ],
    },
    commute: {
      estimatedMinutes: 20,
      peakMinutes: 32,
      distanceKm: 4.8,
      mode: "Direct bus / Metro / Bike",
      routeDescription: "Via ITPL Main Road or Varthur Road directly to Whitefield tech parks.",
      isEstimate: false,
    },
    gyms: {
      countWithinRadius: 8,
      nearestDistanceKm: 0.5,
      items: [
        {
          id: "gym-bro-1",
          title: "Gold's Gym Brookefield",
          rating: 4.6,
          reviewsCount: 610,
          address: "Kundalahalli Main Rd, Brookefield",
          distanceKm: 0.5,
          category: "Full Service Gym & Cardio",
          link: "https://www.google.com/maps/search/Golds+Gym+Brookefield",
        },
        {
          id: "gym-bro-2",
          title: "Cult.fit AECS Layout",
          rating: 4.7,
          reviewsCount: 450,
          address: "AECS Layout, Brookefield",
          distanceKm: 0.8,
          category: "Fitness Center",
          link: "https://www.google.com/maps/search/Cult+fit+AECS+Layout",
        },
        {
          id: "gym-bro-3",
          title: "Fitness First Studio",
          rating: 4.4,
          reviewsCount: 180,
          address: "ITPL Main Rd, Brookefield",
          distanceKm: 1.0,
        },
      ],
    },
    restaurants: {
      countFound: 38,
      vibe: "Vibrant dining strip: Punjabi dhabas, Andhra messes, craft breweries, and trendy bakeries",
      topHighlights: [
        {
          id: "res-bro-1",
          title: "Meghana Foods Brookefield",
          rating: 4.5,
          reviewsCount: 4800,
          address: "Kundalahalli Gate, Brookefield",
          priceLevel: "₹₹",
          snippet: "Legendary spicy Andhra Biryani and chicken 65; constant crowd favorite.",
          link: "https://www.google.com/maps/search/Meghana+Foods+Brookefield",
        },
        {
          id: "res-bro-2",
          title: "Windmills Craftworks",
          rating: 4.7,
          reviewsCount: 5200,
          address: "Near KTPO, Whitefield / Brookefield border",
          priceLevel: "₹₹₹",
          snippet: "World-class microbrewery, live jazz lounge, and fine dining.",
          link: "https://www.google.com/maps/search/Windmills+Craftworks+Whitefield",
        },
        {
          id: "res-bro-3",
          title: "Truffles AECS Layout",
          rating: 4.6,
          reviewsCount: 2900,
          address: "AECS Layout A Block",
          priceLevel: "₹₹",
          snippet: "Iconic burgers, steaks, and desserts frequented by young tech crowds.",
        },
      ],
    },
    groceries: {
      countFound: 16,
      quickCommerceAvailable: true,
      items: [
        {
          id: "groc-bro-1",
          title: "Star Bazaar Hypermarket",
          rating: 4.5,
          reviewsCount: 1850,
          address: "Brookefield Mall, ITPL Main Rd",
          distanceKm: 0.7,
        },
        {
          id: "groc-bro-2",
          title: "Spar Hypermarket & Food Hall",
          rating: 4.4,
          reviewsCount: 1200,
          address: "ITPL Main Rd",
          distanceKm: 1.2,
        },
      ],
    },
    transit: {
      nearestMetroStation: "Kundalahalli Metro Station",
      metroDistanceKm: 0.9,
      hasDirectBus: true,
      transitItems: [
        {
          id: "trans-bro-1",
          title: "Kundalahalli Metro Station (Purple Line)",
          rating: 4.6,
          distanceKm: 0.9,
        },
        {
          id: "trans-bro-2",
          title: "Kundalahalli Gate Bus Terminus",
          distanceKm: 0.4,
          snippet: "Major interchange connecting to Outer Ring Road, Marathahalli, and Whitefield.",
        },
      ],
    },
    reviewThemes: [
      {
        sentiment: "positive",
        topic: "Food & Social Life",
        text: "Unbeatable selection of eateries, AECS layout food street, and nightlife spots.",
        sampleCount: 65,
      },
      {
        sentiment: "positive",
        topic: "Metro Access",
        text: "Kundalahalli metro makes moving across Bangalore effortless.",
        sampleCount: 42,
      },
      {
        sentiment: "negative",
        topic: "Traffic Congestion",
        text: "Kundalahalli Gate underpass still experiences heavy congestion during rush hours.",
        sampleCount: 38,
      },
    ],
    pros: [
      "Outstanding food and social scene with AECS Layout food walk",
      "Gold's Gym and Cult.fit both within 800m",
      "Walking distance (<900m) to Kundalahalli Metro Station",
      "Multiple hypermarkets (Star Bazaar & Spar) close by",
    ],
    cons: [
      "Furnished 1BHK rents (₹24k–₹28k) push near the upper boundary of your ₹25k budget",
      "Kundalahalli Gate intersection is notoriously crowded during peak evening commute",
    ],
    sources: [
      {
        title: "Google Local - Gyms in Brookefield AECS Layout",
        url: "https://www.google.com/maps/search/gyms+brookefield+aecs+layout",
        query: "gyms in Brookefield AECS layout",
        engine: "google_local",
        accessedAt: "2026-09-18T10:42:00Z",
        isCachedDemo: true,
      },
      {
        title: "Google Local - Restaurants Kundalahalli Gate",
        url: "https://www.google.com/maps/search/restaurants+kundalahalli+gate",
        query: "best restaurants Kundalahalli Gate Bangalore",
        engine: "google_local",
        accessedAt: "2026-09-18T10:44:00Z",
        isCachedDemo: true,
      },
    ],
  },

  {
    id: "kundalahalli",
    name: "Kundalahalli Colony",
    city: "Bangalore",
    coordinates: {
      lat: 12.9691,
      lng: 77.7176,
    },
    overview:
      "A well-structured colony located right next to Brookefield, close to CMRIT and Ryan International School. Offers a sweet spot between budget-friendly housing, tech-friendly coliving spaces, and immediate metro access.",
    estimatedRent: {
      bhk1: { min: 19000, max: 24000 },
      bhk2: { min: 30000, max: 37000 },
      confidence: "verified_market_range",
      sourceSummary: "Survey of standalone apartment rentals and coliving suites (Q3 2026)",
      sources: [
        {
          title: "Housing.com - Kundalahalli Rental Averages",
          url: "https://www.google.com/search?q=kundalahalli+colony+rent+averages",
          query: "Kundalahalli Bangalore rental market trends 1BHK",
          engine: "google",
          accessedAt: "2026-09-18T10:46:00Z",
          isCachedDemo: true,
        },
      ],
    },
    commute: {
      estimatedMinutes: 16,
      peakMinutes: 26,
      distanceKm: 3.9,
      mode: "Bike / Metro / Auto",
      routeDescription: "Direct drive via ITPL Main Rd or take Purple Line 2 stops to ITPB.",
      isEstimate: false,
    },
    gyms: {
      countWithinRadius: 5,
      nearestDistanceKm: 0.7,
      items: [
        {
          id: "gym-kun-1",
          title: "Slam Fitness Kundalahalli",
          rating: 4.5,
          reviewsCount: 310,
          address: "Kundalahalli Colony Rd",
          distanceKm: 0.7,
          category: "Crossfit & Weight Training",
        },
        {
          id: "gym-kun-2",
          title: "Chisel Fitness Studio",
          rating: 4.4,
          reviewsCount: 195,
          address: "CMRIT College Road",
          distanceKm: 1.1,
        },
      ],
    },
    restaurants: {
      countFound: 28,
      vibe: "Student and engineer friendly pocket with great budget messes, rolls, and shawarmas",
      topHighlights: [
        {
          id: "res-kun-1",
          title: "Empire Restaurant Kundalahalli",
          rating: 4.3,
          reviewsCount: 3200,
          address: "Kundalahalli Junction",
          priceLevel: "₹₹",
          snippet: "Open late into the night for grilled chicken, ghee rice, and rotis.",
        },
        {
          id: "res-kun-2",
          title: "Kabab Magic & Rolls",
          rating: 4.4,
          reviewsCount: 890,
          address: "Colony Main Rd",
          priceLevel: "₹",
        },
      ],
    },
    groceries: {
      countFound: 10,
      quickCommerceAvailable: true,
      items: [
        {
          id: "groc-kun-1",
          title: "Reliance Fresh Kundalahalli",
          rating: 4.2,
          reviewsCount: 750,
          distanceKm: 0.6,
        },
      ],
    },
    transit: {
      nearestMetroStation: "Kundalahalli Metro Station",
      metroDistanceKm: 0.6,
      hasDirectBus: true,
      transitItems: [
        {
          id: "trans-kun-1",
          title: "Kundalahalli Metro Station",
          distanceKm: 0.6,
        },
      ],
    },
    reviewThemes: [
      {
        sentiment: "positive",
        topic: "Affordability",
        text: "Very affordable for young IT professionals; easy to find 1BHKs under ₹23,000.",
        sampleCount: 39,
      },
      {
        sentiment: "negative",
        topic: "Street Parking",
        text: "Interior streets are narrower; car parking can be difficult to find.",
        sampleCount: 19,
      },
    ],
    pros: [
      "Strongest budget fit: furnished 1BHKs easily available at ₹20k–₹23k (leaving cash surplus)",
      "Commute under 26 mins even at peak rush hour",
      "Only 600m to Kundalahalli Metro Station",
      "Abundant affordable daily dining and late-night eats",
    ],
    cons: [
      "Narrower interior residential lanes with limited four-wheeler parking",
      "Slightly fewer premium lifestyle cafes directly in the colony (though Brookefield is next door)",
    ],
    sources: [
      {
        title: "Google Search - Kundalahalli rent and livability index",
        url: "https://www.google.com/search?q=kundalahalli+colony+rent+and+livability+bangalore",
        query: "Kundalahalli colony rent and livability bangalore",
        engine: "google",
        accessedAt: "2026-09-18T10:48:00Z",
        isCachedDemo: true,
      },
    ],
  },

  {
    id: "kadugodi",
    name: "Kadugodi / Hope Farm",
    city: "Bangalore",
    coordinates: {
      lat: 12.9984,
      lng: 77.7612,
    },
    overview:
      "The eastern terminus of Namma Metro Purple Line. Known for larger gated societies, spacious modern layouts, lower pollution, and significantly lower rental rates compared to central Whitefield.",
    estimatedRent: {
      bhk1: { min: 16000, max: 21000 },
      bhk2: { min: 25000, max: 32000 },
      confidence: "verified_market_range",
      sourceSummary: "Aggregated listings across gated societies in Kadugodi (Q3 2026)",
      sources: [
        {
          title: "NoBroker - Kadugodi Gated Society Rent Trends",
          url: "https://www.google.com/search?q=kadugodi+bangalore+rent+trends+nobroker",
          query: "Kadugodi Bangalore 1BHK gated society rent trends",
          engine: "google",
          accessedAt: "2026-09-18T10:50:00Z",
          isCachedDemo: true,
        },
      ],
    },
    commute: {
      estimatedMinutes: 15,
      peakMinutes: 24,
      distanceKm: 3.5,
      mode: "Metro (3 min) / Bike / Auto",
      routeDescription: "1-2 stops on Purple Line directly to ITPB / Pattandur Agrahara station.",
      isEstimate: false,
    },
    gyms: {
      countWithinRadius: 4,
      nearestDistanceKm: 0.9,
      items: [
        {
          id: "gym-kad-1",
          title: "Anytime Fitness Kadugodi",
          rating: 4.6,
          reviewsCount: 220,
          address: "Near Kadugodi Metro Station",
          distanceKm: 0.9,
        },
        {
          id: "gym-kad-2",
          title: "Spartan Power Gym",
          rating: 4.4,
          reviewsCount: 160,
          distanceKm: 1.3,
        },
      ],
    },
    restaurants: {
      countFound: 20,
      vibe: "Family restaurants, fast casual bakeries, and local South Indian eateries",
      topHighlights: [
        {
          id: "res-kad-1",
          title: "A2B - Adyar Ananda Bhavan Kadugodi",
          rating: 4.2,
          reviewsCount: 2100,
          priceLevel: "₹₹",
        },
        {
          id: "res-kad-2",
          title: "Dominos & Pizza Hut Hope Farm",
          rating: 4.1,
          reviewsCount: 950,
          priceLevel: "₹₹",
        },
      ],
    },
    groceries: {
      countFound: 8,
      quickCommerceAvailable: true,
      items: [
        {
          id: "groc-kad-1",
          title: "Loyal World Market Kadugodi",
          rating: 4.4,
          reviewsCount: 520,
          distanceKm: 0.8,
        },
      ],
    },
    transit: {
      nearestMetroStation: "Kadugodi Tree Park / Whitefield Metro Terminus",
      metroDistanceKm: 0.5,
      hasDirectBus: true,
      transitItems: [
        {
          id: "trans-kad-1",
          title: "Whitefield (Kadugodi) Metro Terminal",
          distanceKm: 0.5,
        },
      ],
    },
    reviewThemes: [
      {
        sentiment: "positive",
        topic: "Peace & Space",
        text: "Very peaceful, broad roads, and much more apartment space for the price.",
        sampleCount: 35,
      },
      {
        sentiment: "negative",
        topic: "Nightlife Distance",
        text: "Fewer upscale pubs and late-night cafes compared to Brookefield or Indiranagar.",
        sampleCount: 18,
      },
    ],
    pros: [
      "High rent savings: furnished 1BHK at ₹17k–₹20k (saving ₹5,000–₹8,000/month)",
      "Direct Purple Line metro link to ITPB (under 10 mins door to door)",
      "Tree-lined gated communities with clubhouse amenities",
    ],
    cons: [
      "Quieter neighborhood with fewer late-night pubs or specialty coffee cafes",
      "Hope Farm junction can experience traffic delays if traveling by car",
    ],
    sources: [
      {
        title: "Google Local - Kadugodi Metro and Amenities",
        url: "https://www.google.com/maps/search/amenities+near+kadugodi+metro",
        query: "amenities near Kadugodi metro Bangalore",
        engine: "google_local",
        accessedAt: "2026-09-18T10:52:00Z",
        isCachedDemo: true,
      },
    ],
  },

  {
    id: "hoodi",
    name: "Hoodi",
    city: "Bangalore",
    coordinates: {
      lat: 12.9918,
      lng: 77.7161,
    },
    overview:
      "A fast-developing tech corridor node sitting right between Mahadevapura and central Whitefield. Superb connectivity via Hoodi Metro and railway halt, popular among engineers at Prestige Shantiniketan and ITPL.",
    estimatedRent: {
      bhk1: { min: 22000, max: 27000 },
      bhk2: { min: 34000, max: 42000 },
      confidence: "verified_market_range",
      sourceSummary: "Listing aggregates around Hoodi Circle and ITPL main road (Q3 2026)",
      sources: [
        {
          title: "99acres - Hoodi Locality Trends",
          url: "https://www.google.com/search?q=hoodi+bangalore+rent+trends+99acres",
          query: "Hoodi Bangalore 1BHK rent trends 99acres",
          engine: "google",
          accessedAt: "2026-09-18T10:54:00Z",
          isCachedDemo: true,
        },
      ],
    },
    commute: {
      estimatedMinutes: 14,
      peakMinutes: 22,
      distanceKm: 2.8,
      mode: "Direct Metro (1 stop) / Two-wheeler / Cab",
      routeDescription: "1.5 km to Prestige Shantiniketan, 2.8 km to ITPB via ITPL Main Rd.",
      isEstimate: false,
    },
    gyms: {
      countWithinRadius: 5,
      nearestDistanceKm: 0.8,
      items: [
        {
          id: "gym-hoo-1",
          title: "Golds Gym Hoodi",
          rating: 4.5,
          reviewsCount: 340,
          distanceKm: 0.8,
        },
        {
          id: "gym-hoo-2",
          title: "F45 Training Hoodi",
          rating: 4.8,
          reviewsCount: 180,
          distanceKm: 1.4,
        },
      ],
    },
    restaurants: {
      countFound: 25,
      vibe: "Tech-park food courts, North Indian bistros, and trendy breweries near Shantiniketan",
      topHighlights: [
        {
          id: "res-hoo-1",
          title: "The Forum Shantiniketan Food Court & Breweries",
          rating: 4.6,
          reviewsCount: 4100,
          distanceKm: 1.2,
          priceLevel: "₹₹",
        },
      ],
    },
    groceries: {
      countFound: 11,
      quickCommerceAvailable: true,
      items: [
        {
          id: "groc-hoo-1",
          title: "Star Market Hoodi Circle",
          rating: 4.3,
          reviewsCount: 610,
          distanceKm: 0.5,
        },
      ],
    },
    transit: {
      nearestMetroStation: "Hoodi Metro Station",
      metroDistanceKm: 0.4,
      hasDirectBus: true,
      transitItems: [
        {
          id: "trans-hoo-1",
          title: "Hoodi Metro Station (Purple Line)",
          distanceKm: 0.4,
        },
      ],
    },
    reviewThemes: [
      {
        sentiment: "positive",
        topic: "Work Proximity",
        text: "You can practically cycle or walk to Prestige Shantiniketan and ITPL.",
        sampleCount: 52,
      },
      {
        sentiment: "negative",
        topic: "Dust & Construction",
        text: "Ongoing commercial construction around Hoodi junction causes dust.",
        sampleCount: 26,
      },
    ],
    pros: [
      "Fastest commute to Prestige Shantiniketan / ITPL (under 15-20 mins)",
      "Only 400m to Hoodi Metro Station",
      "Proximity to Forum Shantiniketan mall and dining hub",
    ],
    cons: [
      "Higher rents due to direct walking proximity to major tech parks",
      "Hoodi circle intersection is noisy and experiences dust from ongoing construction",
    ],
    sources: [
      {
        title: "Google Local - Hoodi Infrastructure and Commute",
        url: "https://www.google.com/maps/search/hoodi+metro+station+bangalore",
        query: "Hoodi metro station and tech parks Bangalore",
        engine: "google_local",
        accessedAt: "2026-09-18T10:56:00Z",
        isCachedDemo: true,
      },
    ],
  },
];

export const DEMO_TEMPORARY_HOTELS: HotelItem[] = [
  {
    id: "hotel-1",
    title: "Vivanta Bengaluru, Whitefield",
    pricePerNightInr: 6800,
    priceFormatted: "₹6,800/night",
    rating: 4.6,
    reviewsCount: 4320,
    distanceToOfficeKm: 0.4,
    distanceDescription: "400m from ITPB gate (walkable)",
    neighborhood: "Whitefield Main Rd",
    thumbnail: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500&auto=format&fit=crop&q=60",
    link: "https://www.google.com/travel/hotels/entity/ChgI2qL3n6z...",
    amenities: ["Free High-Speed WiFi", "24/7 Gym", "Swimming Pool", "Airport Shuttle", "Breakfast Included"],
    sourceEngine: "google_hotels",
  },
  {
    id: "hotel-2",
    title: "Keys Select by Lemon Tree Hotels, Whitefield",
    pricePerNightInr: 3200,
    priceFormatted: "₹3,200/night",
    rating: 4.2,
    reviewsCount: 2950,
    distanceToOfficeKm: 1.8,
    distanceDescription: "1.8 km from ITPB (7 min cab)",
    neighborhood: "Brookefield / ITPL Rd",
    thumbnail: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500&auto=format&fit=crop&q=60",
    link: "https://www.google.com/travel/hotels/entity/ChgI3qL3n6z...",
    amenities: ["Free WiFi", "Fitness Center", "Work Desk", "Restaurant", "Express Laundry"],
    sourceEngine: "google_hotels",
  },
  {
    id: "hotel-3",
    title: "Holiday Inn Express Bengaluru Whitefield ITPL",
    pricePerNightInr: 3900,
    priceFormatted: "₹3,900/night",
    rating: 4.4,
    reviewsCount: 2180,
    distanceToOfficeKm: 1.1,
    distanceDescription: "1.1 km to tech parks",
    neighborhood: "Near Nallurhalli / ITPL",
    thumbnail: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=500&auto=format&fit=crop&q=60",
    link: "https://www.google.com/travel/hotels/entity/ChgI4qL3n6z...",
    amenities: ["Complimentary Express Breakfast", "Power Showers", "Free WiFi", "Business Center"],
    sourceEngine: "google_hotels",
  },
  {
    id: "hotel-4",
    title: "Bloomrooms @ Whitefield",
    pricePerNightInr: 2700,
    priceFormatted: "₹2,700/night",
    rating: 4.3,
    reviewsCount: 1640,
    distanceToOfficeKm: 2.4,
    distanceDescription: "2.4 km from Whitefield center",
    neighborhood: "Brookefield Main Rd",
    thumbnail: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=500&auto=format&fit=crop&q=60",
    link: "https://www.google.com/travel/hotels/entity/ChgI5qL3n6z...",
    amenities: ["Crisp Queen Bed", "Free Fast WiFi", "Cafe", "iMac Stations"],
    sourceEngine: "google_hotels",
  },
];
